---

- hosts: all
  become: true
  become_method: su
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  become_method: su
  tasks:

  - name: install apache and php package for Debian servers
    tags: debian,apache,apache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: install apache and php package for Centos servers
    tags: centos, apache, httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
- hosts: db_servers
  become: true
  become_method: su
  tasks:


  - name: install mariadb package (Debian)
    tags: debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  become_method: su
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
