- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key:  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDDlCWVdKfe3Fo2lGHGDCY+4cDAhge4iHPqkuISk78PB ansible" 

- name: generate sshd_sonfig file from a template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd.config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
